# -*- coding: utf-8 -*-
"""Med-Bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CU9zBsi0SxJQZ-P8awqc6wJLBtaqp2_o
"""

!pip install langchain

!pip install streamlit

!pip install PyPDF2

pip install -U langchain-community

import streamlit as st
from PyPDF2 import PdfReader
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.chains import RetrievalQA
#from ui import css, bot_template, user_template
from langchain.llms import CTransformers
from langchain import PromptTemplate

!pip install ctransformers

!pip install sentence-transformers

llm = CTransformers(
                model = "TheBloke/Llama-2-7B-Chat-GGML",
                model_type="llama",
                max_new_tokens = 512,
                temperature = 0.9
            )

hfembeddings = HuggingFaceEmbeddings(
                            model_name="thenlper/gte-large",
                            model_kwargs={'device': 'cpu'}
                        )

!pip install faiss-gpu

vectorstore = FAISS.load_local(
    "/content/faissmedical",
    hfembeddings,
    allow_dangerous_deserialization=True
)

retrieval_qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectorstore.as_retriever(),
    return_source_documents=True,
    chain_type_kwargs={"prompt": custom_prompt_temp}

)

def get_pdf_text(pdf_docs):
    text = ""
    for pdf in pdf_docs:
        pdf_reader = PdfReader(pdf)
        for page in pdf_reader.pages:
            text += page.extract_text()
    return text

!wget -q -O - ipv4.icanhazip.com

! streamlit run main.py & npx localtunnel --port 8501